### ISSUE TITLE
Unable to build extension on an M1 Mac running Sequoia 15.5

### ISSUE THREAD

**Issue by MichaelSims** [Query-farm/airport#18]
Hi,
I am attempting to build the extension following the README instructions. My particulars:
- M1 Mac
- Sequoia 15.5
- `cmake` version 4.0.2 installed via Homebrew
- `ninja` version 1.12.1 installed via Homebrew

I clone the repos, bootstrap vcpkg then run `GEN=ninja make`. vcpkg is apparently attempting to compile the "abseil" dependency and failing with:
```
unscaledcycleclock.h:39:10: fatal error: 'cstdint' file not found 
   39 | #include <cstdint> 
      |          ^~~~~~~~~ 
```

I will attach a full log with paths redacted:
[iTerm2 Session May 30, 2025 at 12:29:02 PM.txt](https://github.com/user-attachments/files/20524655/iTerm2.Session.May.30.2025.at.12.29.02.PM.txt)

Thank you in advance for any assistance.

**Comment by rustyconover** [comment]
Hi @MichaelSims,

Sorry to hear you're running into trouble building Airport! I'm using a very similar setup on macOS 15.5, so hopefully we can figure this out quickly.

One possibility is that gcc is being used instead of clang — it might be worth double-checking your Xcode Command Line Tools setup.

Just a heads-up: Abseil is a third-party dependency and not something I've modified as part of Airport, so it typically builds without issue. That said, I’m happy to help troubleshoot further if I can — just let me know!

Best,
Rusty

**Comment by MichaelSims** [comment]
Thank you. It looks like I am using Apple clang:
```shell
❯ xcode-select -p 
/Library/Developer/CommandLineTools 
❯ xcrun -f c++ 
/Library/Developer/CommandLineTools/usr/bin/c++ 
❯ ls -la `!!` 
❯ ls -la `xcrun -f c++` 
lrwxr-xr-x  1 root  wheel  5 May 28 21:06 /Library/Developer/CommandLineTools/usr/bin/c++ -> clang 
❯ c++ --version 
Apple clang version 17.0.0 (clang-1700.0.13.5) 
Target: arm64-apple-darwin24.5.0 
Thread model: posix 
InstalledDir: /Library/Developer/CommandLineTools/usr/bin 
❯ xcrun --show-sdk-path 
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk 
❯ ls -la `!!` 
❯ ls -la `xcrun --show-sdk-path` 
lrwxr-xr-x  1 root  wheel  14 May 28 21:08 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -> MacOSX15.5.sdk 
```
I even did this:
```shell
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
```
And I got the same failure, the only difference was the command in the log was explicitly `/usr/bin/clang++`

For kicks, I tried to build using clang from llvm 19.1.7 installed via homebrew (I also had to install "bison" required by one of the deps, I forget which one). Doing that I was able to compile all the dependencies. Now I'm hitting an error compiling airport_flight_stream.cpp:
```
/opt/homebrew/Cellar/llvm@19/19.1.7/bin/../include/c++/v1/__memory/allocator.h:165:24: error: no matching constructor for initialization of 'arrow::io::BufferReader' 
  165 |     ::new ((void*)__p) _Up(std::forward<_Args>(__args)...); 
      |                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
```
More context:
```
[5/205] Building CXX object extension/airport/CMakeFiles/airport_extension.dir/src/airport_flight_stream.cpp.o 
FAILED: extension/airport/CMakeFiles/airport_extension.dir/src/airport_flight_stream.cpp.o  
/opt/homebrew/Cellar/llvm@19/19.1.7/bin/clang++ -DCURL_STATICLIB -DDUCKDB_BUILD_LIBRARY -DEXT_VERSION_AIRPORT=\"0386062\" -DMSGPACK_DEFAULT_API_VERSION=3 -DMSGPACK_NO_BOOST -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/src/include -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/fsst -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/fmt/include -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/hyperloglog -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/fastpforlib -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/skiplist -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/fast_float -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/re2 -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/miniz -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/utf8proc/include -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/concurrentqueue -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/pcg -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/tdigest -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/mbedtls/include -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/jaro_winkler -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/yyjson/include -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/zstd/include -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/src/include -I/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/third_party/libpg_query/include -isystem /Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/build/release/vcpkg_installed/arm64-osx/include -O3 -DNDEBUG -O3 -DNDEBUG   -std=c++17 -arch arm64 -fPIC -fcolor-diagnostics -MD -MT extension/airport/CMakeFiles/airport_extension.dir/src/airport_flight_stream.cpp.o -MF extension/airport/CMakeFiles/airport_extension.dir/src/airport_flight_stream.cpp.o.d -o extension/airport/CMakeFiles/airport_extension.dir/src/airport_flight_stream.cpp.o -c /Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/src/airport_flight_stream.cpp 
In file included from /Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/src/airport_flight_stream.cpp:1: 
In file included from /Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/src/include/airport_flight_stream.hpp:5: 
In file included from /Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/src/include/duckdb/common/arrow/arrow_wrapper.hpp:11: 
In file included from /Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/src/include/duckdb/common/helper.hpp:11: 
In file included from /Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/duckdb/src/include/duckdb/common/constants.hpp:11: 
In file included from /opt/homebrew/Cellar/llvm@19/19.1.7/bin/../include/c++/v1/memory:940: 
/opt/homebrew/Cellar/llvm@19/19.1.7/bin/../include/c++/v1/__memory/allocator.h:165:24: error: no matching constructor for initialization of 'arrow::io::BufferReader' 
  165 |     ::new ((void*)__p) _Up(std::forward<_Args>(__args)...); 
      |                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
/opt/homebrew/Cellar/llvm@19/19.1.7/bin/../include/c++/v1/__memory/allocator_traits.h:319:9: note: in instantiation of function template specialization 'std::allocator<arrow::io::BufferReader>::construct<arrow::io::BufferReader, const std::string &>' requested here 
  319 |     __a.construct(__p, std::forward<_Args>(__args)...); 
      |         ^ 
/opt/homebrew/Cellar/llvm@19/19.1.7/bin/../include/c++/v1/__memory/shared_ptr.h:264:33: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<arrow::io::BufferReader>>::construct<arrow::io::BufferReader, const std::string &, 0>' requested here 
  264 |     allocator_traits<_TpAlloc>::construct(__tmp, __get_elem(), std::forward<_Args>(__args)...); 
      |                                 ^ 
/opt/homebrew/Cellar/llvm@19/19.1.7/bin/../include/c++/v1/__memory/shared_ptr.h:843:51: note: in instantiation of function template specialization 'std::__shared_ptr_emplace<arrow::io::BufferReader, std::allocator<arrow::io::BufferReader>>::__shared_ptr_emplace<const std::string &, std::allocator<arrow::io::BufferReader>, 0>' requested here 
  843 |   ::new ((void*)std::addressof(*__guard.__get())) _ControlBlock(__a, std::forward<_Args>(__args)...); 
      |                                                   ^ 
/opt/homebrew/Cellar/llvm@19/19.1.7/bin/../include/c++/v1/__memory/shared_ptr.h:851:15: note: in instantiation of function template specialization 'std::allocate_shared<arrow::io::BufferReader, std::allocator<arrow::io::BufferReader>, const std::string &, 0>' requested here 
  851 |   return std::allocate_shared<_Tp>(allocator<__remove_cv_t<_Tp> >(), std::forward<_Args>(__args)...); 
      |               ^ 
/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/src/airport_flight_stream.cpp:58:31: note: in instantiation of function template specialization 'std::make_shared<arrow::io::BufferReader, const std::string &, 0>' requested here 
   58 |     auto buffer_reader = std::make_shared<arrow::io::BufferReader>(function_call_data.data); 
      |                               ^ 
/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/build/release/vcpkg_installed/arm64-osx/include/arrow/io/memory.h:145:20: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const std::string' to 'const BufferReader' for 1st argument 
  145 | class ARROW_EXPORT BufferReader 
      |                    ^~~~~~~~~~~~ 
/Users/michael.sims/IdeaProjects/misc/airport-building/duckdb-airport-extension/build/release/vcpkg_installed/arm64-osx/include/arrow/io/memory.h:151:12: note: candidate constructor not viable: no known conversion from 'const std::string' to 'std::shared_ptr<Buffer>' for 1st argument 
  151 |   explicit BufferReader(std::shared_ptr<Buffer> buffer); 
      |            ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
1 error generated. 
[16/205] Building CXX object extension/airport/CMakeFiles/airport_extension.dir/src/airport_flight_statistics.cpp.o 
ninja: build stopped: subcommand failed. 
make: *** [release] Error 1 
```
Am I barking up the wrong tree, trying to use homebrew-installed llvm 19.1.7 ?

Thanks!

**Comment by rustyconover** [comment]
I just committed a fix for the compilation error dealing with
arrow::io::BufferReader, when you checked out vcpkg it brings in a newer
version of the Apache Arrow than what I was using.  I just updated mine and
fixed the same error.

Thanks,

Rusty

**Comment by MichaelSims** [comment]
I was able to build successfully after pulling latest changes. Thanks for your help!
